### PR TITLE
Update to Swift 5

### PR DESCRIPTION
**Pull request by lm2343635**
Fix some warnings and update the Swift version to 5.0

### CODE REVIEW

**Comment by Jiar** [comment]
Thanks for contribution!

But some things are not handled well enough:
- why delete `- gem install xcpretty --no-rdoc --no-ri --no-document --quiet` `- gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet`
- why change `IPHONEOS_DEPLOYMENT_TARGET`
- should merge to `v2` branch

**Comment by lm2343635** [comment]
- In order to fix the travis test building, I deleted `- gem install xcpretty --no-rdoc --no-ri --no-document --quiet - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet`.
- SnapKit 5 requires iOS 10.0

**Comment by Jiar** [comment]
Delete it is not a right way, `xcpretty` is need to be used.

**Comment by lm2343635** [comment]
The `osx_image: xcode10.1` provided by Travis installed the `pretty` command.
So we need not to install it again.

**Comment by Jiar** [comment]
Thanks to explain!

Another problem is that I found there is nothings in the picture shown below.
no_travis_icon

**Comment by lm2343635** [comment]
I may push the first two commits at the same time.
I forgot it because I created this PR about 1 month ago.

**Comment by Jiar** [comment]
I have got it.

please change to merge to `v2` branch.

**Comment by lm2343635** [comment]
DONE

**Comment by Jiar** [comment]
[The Travis CI build failed](https://travis-ci.org/Jiar/SegementSlide/jobs/545529792), please check it.

**Comment by Jiar** [comment]
I think this problem was caused by a commit([Merge branch 'v2' into master](https://github.com/lm2343635/SegementSlide/commit/cf7a0467afe30e1225234a105b35d2ec52798bf4))
It retain the code `override var headerHeight: CGFloat? {` in the file `ExploreViewController.Swift`.

Please check it carefully.

**Comment by Jiar** [comment]
@lm2343635

**Comment by Jiar** [comment]
Since the problem has not been addressed for a long time, I will close this issue first.

**Pull request closed without merging**
