### PR TITLE
full screen support

### PR DESCRIPTION
**Pull request by czqasngit**

### CODE REVIEW

**Comment by Jiar** [comment]
Thanks for contribution!

There are some questions:

- It’s better to `git pull` before `pull request`, otherwise may cause modify that not needed.
- I found that you add the `innerHeaderTopLength` property, and comment as: `the distance between header and root scrollview`, but why should add it? (you can add the distance in header)
- The `innerHeaderTopLength` property contain `inner` but mark as `open`, that's not a good way to name it.
- Change `COCOAPODS` to a beta version is not a good idea.
- Now, it’s version 2, you should merge to `v2` branch.

**Comment by czqasngit** [comment]
Thank you for your response.
There has some question when UINavigationBar has hidden.
There is a distance between window top and scrollview.

**Comment by Jiar** [comment]
You can look at the `HomeViewController` in the `Example` project, which demonstrates the hidden display of the navigationBar. But I don't see any problem with it.

"when UINavigationBar has hidden", it's a problem about safeArea, I had solved this problem. So I think `innerHeaderTopLength` is not necessary.

If you still have some questions, you can provide a demo about problem to me.

**Comment by czqasngit** [comment]
image
image
头部背景需要填充满,而不是留一个safe top height

**Comment by czqasngit** [comment]
image

**Comment by Jiar** [comment]
- 目前的`SegementSlide`是可以支持『头部背景需要填充满』的，你需要继承`TransparentSlideViewController`来使用，而不是用`SegementSlideViewController`。如果`TransparentSlideViewController`的样式不满足你的需求，可以继承`SegementSlideViewController`来实现一个自定义类，该自定义类可以模仿`TransparentSlideViewController`的写法，如果需要『头部背景需要填充满』，请务必在自定义类的`edgesForExtendedLayout`属性中包含`.top`值。
- 另外，在该`pull request`申请之后的一段时间，我曾经为了移除仓库历史中的大资源文件而重写了机率，导致目前的`pull request`存在冲突，不能直接合并，如果今后有更好的建议，可以提交到当前版本的分支下，如：现在是`v2`分支。
- 建议`commit`以英文编写，保持国际化。
- `commit`应该保持功能一致，如：[no message](https://github.com/Jiar/SegementSlide/pull/4/commits/8502701739ed10ca77adb96d324d9b65a332a770)应该属于[WKWebView也需要响应内部点击事件,比如视频播放](https://github.com/Jiar/SegementSlide/pull/4/commits/3963ad5c0bc5574a26bf94dc5ab42f9be94ae682)的一部分，应该合为一个。

**Comment by czqasngit** [comment]
OK

**Pull request closed without merging**
